#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Nov 25 02:35:41 EST 2023
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -d "FUNCTIONAL=" -d "SIM=" -d "DUNIT_DELAY=1" -d "USE_POWER_PINS=" -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot counter_wb_tb_behav xil_defaultlib.counter_wb_tb xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -d "FUNCTIONAL=" -d "SIM=" -d "DUNIT_DELAY=1" -d "USE_POWER_PINS=" -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot counter_wb_tb_behav xil_defaultlib.counter_wb_tb xil_defaultlib.glbl -log elaborate.log

